name: 1. Convert Upstream Rules (7:30 AM)

on:
  workflow_dispatch:
  schedule:
    # 每天 UTC 23:30 运行 (北京时间 7:30)
    - cron: "30 23 * * *"

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 只需要基本的写入权限
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run converter.py script
        run: python Loon/converter.py

      - name: Commit and Push converted list
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Loon/generated/
          if ! git diff --staged --quiet; then
            git commit -m "build(auto): 更新转换后的规则列表"
            git push
          else
            echo "No changes in converted rules. Nothing to push."
          fi
